config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  post '/' => 'users#search'
  get '/home' => 'pages#home'
  post '/home/all' => 'pages#feed'
  get '/home/all' => 'pages#feed'
  post '/home/popular' => 'pages#popular'
  get '/home/popular' => 'pages#popular'


  get '/login' => 'session#new'         # login form
  post '/login' => 'session#create'     # performs login, redirect
  delete '/login' => 'session#destroy'  # logout, redirect 

  get '/users/new' => 'users#new'
  post '/users/:id/edit' => 'users#edit' 
  post '/users/:id/likes/:id' => 'likes#show'
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  get '/users/:id/following' => 'following#show'
  get '/users/create'
  get '/users/destroy'

  post '/reviews/:id' => 'reviews#show'

  resources :comments
  resources :lists


  resources :users do
    resources :followers, :following
  end


  resources :reviews do 
    resources :likes, :comments
  end


end

app/models/user.rb
class User < ApplicationRecord # notes from Luke's lesson -->

    # before_destroy :destroy_associated_items
    has_secure_password

    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy


    has_and_belongs_to_many :lists
    
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true, uniqueness: true

    # We want users to be able to follow other users
    # This creates two different relationships, since a follow is not 'symmetrical'
    # You can follow another user, without that user following you back 
    # i.e. we want to have 
        # u1.followers - the users that are following u1
        # u2.following - the users that u1 is following 

    # We actually need to create another model - follow
    # ... this will be like a kind of join table, but its also a model 


    # This lets us write
    # User.first.following.relationships
    # to get a list of who this user is following, BUT you get an array 
    # of Follow objects, so to get to the User object you are following,
    # you need to write something awkward like 
    #   User.first.following_relationships.first.followed 
    has_many :following_relationships, class_name: 'Follow', foreign_key: 'follower_id'
    has_many :followed_relationships, class_name: 'Follow', foreign_key: 'followed_id'

    # If we add a 'through' association, then we get the 'User.first.following' syntax 
    # we want, AND it will be a list of actual User objects (not Follow objects)
    has_many :following, through: :following_relationships, source: :followed
    has_many :followers, through: :followed_relationships, source: :follower     

    # So now we can ask "who is the first user following?" by writing
    #       User.first.following
    # and we get an array of User objects
    # 
    # AND we have a nice syntax for adding a follow, the same as a many-to-many association:
    # 
    # User.first.following << User.second
    # 
    # (which you could also write as) User.second.followers << User.first
    # 
    # i.e. the Follow model is now invisible/transparent - we never really need to 
    # talk to it directly, we use our new User associations following/followers instead 


    # !!!!! User.first.following.include? User.second !!!!!


    # Let's add a model method that lets a user follow another user, But also checks
    # that they aren't already following them (i.e. avoid duplicates)
    # i.e. we will run @current_user.follow_safe(@other_user)
    # ... in the above example, we can access @current_user inside the method
    # as 'self' (which is like Javascripts's 'this')
    def follow_safe( user_to_follow )
        
        if self.following.include? user_to_follow
            return false
        else
            self.following << user_to_follow
           return true
       end # if/else 

    end # follow_safe

    def following_reviews
        Review.where user: self.following 
        # TODO: look up 'User.joins(:reviews)' for a preferred syntax 
    end
    # Review.where user_id: User.first.following.ids

    private 
    def destroy_associated_items
        puts "hello"
        likes.destroy_all
        reviews.destroy_all
        true
    end #destroy_associated_items

end # class User

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end # new()

  def search
    @user = User.find_by username: params[:search]
    redirect_to user_path(@user.id)
  end # search()

  def create
    @user = User.create user_params

    if @user.valid?
      session[:user_id] = @user.id
      @userimg = Identicon.data_url_for @user.username, 400
      @user.update! image: @userimg
      @user.setimage = false 
      redirect_to home_path
      
    else
      flash[:error] = 'Invalid email or password'
      redirect_to new_user_path
    end # create() if/else

  end #create()

  def edit
    @user = User.find params[:id]
  end # edit()

  def update

    @current_user.bio = params[:user][:bio]
    @current_user.birthday = params[:user][:birthday]
    @current_user.setimage = true 

    if params[:user][:image].present?
      response = Cloudinary::Uploader.upload(params[:user][:image])
      @current_user.image=response['public_id']
    end

    @current_user.save
    redirect_to user_path(params[:id])
    
  end # update()

  def destroy
  end

  def follow
    @user = User.find(params[:id])
    @current_user.following << @user
    redirect_back(fallback_location: user_path(@user))
  end # follow()
  
  def unfollow
    @user = User.find(params[:id])
    Follow.find_by(follower_id: @current_user.id, followed_id:@user.id).destroy
    # @current_user.following.find_by(followed_id: @user.id).destroy
    redirect_back(fallback_location: user_path(@user))
  end # unfollow()

  def show
    @user = @current_user
    @userinfo = User.find params[:id]
    @user_reviews = @userinfo.reviews.order(created_at: :desc)
    @userimg = Identicon.data_url_for @userinfo.username, 400
  end # show()

  private
  def user_params
     params.require(:user).permit(:username, :image, :email, :password)
  end # user_params()

end # UsersController

app/views/users/_form.html.erb
<%= form_with model: @user, local:true, html:{multipart:true} do |f| %>

    <%= f.file_field :image%>

    <%= f.label :bio, :class => 'form-label', class:'form-label' %>
    <%= f.text_field :bio, :maxlength => 140%>
    <%= f.date_field :birthday, value: f.object.try(:strftime,"%Y/%m/%d") %>

    <%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h1>EDIT YOUR ( @<%= @current_user.username %> ) PROFILE!!</h1>

<%= render partial: 'form' %>

app/views/users/new.html.erb
<%= yield :nothing %>
<% content_for :signup do %>
    <link rel="stylesheet" href="/signup.css" >
<% end %>

<% if flash[:error] %>
    <%= flash[:error] %>
<% end %>


<div class="circle"></div>

<div class="container signup">
    <%= form_with model: @user, local:true do |f| %>
        <div class="row">
            <h1 class="newacc">CREATE A NEW ACCOUNT</h1>
        </div>

        <div class="row">
            <%= f.text_field :username, :maxlength => 15, placeholder:'username', autocomplete:"off", class:"newuser" %>
        </div>

        <div class="row">
            <%= f.text_field :email, placeholder:'email', class:"newemail" %>
        </div>

        <div class="row">
            <%= f.password_field :password, placeholder:'password', class:"newemail" %>
        </div>

        <div class="row">
            <%= f.submit 'Sign up', class:"existbtn custbtn signupbtn" %>
        </div>

    <% end %>

    <h5 class="existacc">Already have an account?</h5>
    <%= button_to 'Sign in', login_path, class:"existbtn custbtn signinbtn"%>
</div>

app/views/users/show.html.erb
<div class="darkmode"></div>

<div class="profile-header">
    
    <div class="header-img">
    </div>

    <p>
    <h1 class="user-page"><%= @userinfo.username%>'s profile</h1>
    </p>

    <div class="profile-page-image">
    <% if @userinfo.setimage %>
        <%= cl_image_tag @userinfo.image %>
    <% else %>
        <%= image_tag @userinfo.image %>
    <% end %>

    </div>



    <div class="flwbtn">
        <% unless @userinfo.id == @current_user.id %>
            <% if @current_user.following.include? @userinfo %>
                <%= button_to "UNFOLLOW", unfollow_user_path, method: "POST", class:"btn btn-outline-danger" %>
            <% else %>
                <%= button_to "FOLLOW", follow_user_path, method: "POST", class:"btn btn-outline-primary"%>
            <% end %>
            <%# copy the like path stuff for this %>
        <% end %>

            <% if @current_user.present? %>
                <% if @current_user.id == @userinfo.id %>
                    <%= button_to "preferences", edit_user_path(@current_user) %>
                    <%# <%= button_to "user likes", user_like_path(@userinfo) %> 
                <% end %>
            <% end %>
    </div>

    <% if @userinfo.bio.present? %>
        <div class="userbio">
            <p>
                <%= @userinfo.bio %>
            </p>
        </div>
    <% end %>

    <p class="follow">
        <%= link_to "Followers: #{@userinfo.followers.count}", user_followers_path(@userinfo.id) %>
        <%= link_to "Following: #{@userinfo.following.count}", user_following_path(@userinfo.id) %>
    </p>


    <% if @userinfo.birthday.present?  %>
        <div class="userbirth">
           <p>
                <%= @userinfo.birthday %>
           </p> 
        </div>
    <% end %>



    <%# TURN THIS INTO A FORM!! %>
    <% if @user_reviews.count == 0 %>
        <div class="reviewblock usercont">
            <div class="content">
                <p>
                    this user hasn't posted anything yet 
                </p>
            </div>
        </div>
    <% end %>

    <% @user_reviews.each do |r| %>
        <div class="reviewblock usercont">
            <div class="userimg">
                <%= cl_image_tag r.user.image, width:'25'%>
            </div>

            <div class="title">
                <p>
                    <%= link_to r.title, review_path(r.id) %>
                </p>
            </div>

            <div class="user">
                <p>
                    <%= link_to '@' + r.user.username.to_s, user_path(r.user.id) %>
                </p>
            </div>

            <div class="content">
                <p>
                    <%= r.rating %>
                </p>

                <% unless r.image == nil %>
                    <div class="post-image">
                        <%= cl_image_tag r.image %>
                    </div>
                <% end %>
            </div>

            <div class="create_time">
                <p>
                    <%= r.created_at.strftime("%H:%M, %Y-%m-%d") %>
                </p>
            </div>

            <div class = "up">
                <% pre_like = r.likes.find { |like| like.user_id == @current_user.id} %>
                <% if pre_like %>
                    <%= button_to '❤️', review_like_path(r.id, pre_like), method: :delete, class:"likebtn" %>
                <% else %>
                    <%= button_to '🤍', review_likes_path(r.id), method: :post, class:"likebtn"%>
                <% end %>
            </div>

            <div class="count">
                <p>
                    <%= r.likes.count %> 
                </p>
            </div>

            <div class="edit">
                <% if @current_user.id == r.user.id%>
                    <%= link_to "DELETE", review_path(r.id), method:'delete' %>
                <% end %>
            </div>

        </div> <%# review block %>

    <% end %> <%# user review each %>

</div>