config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  post '/' => 'users#search'
  get '/home' => 'pages#home'
  post '/home/all' => 'pages#feed'
  get '/home/all' => 'pages#feed'
  post '/home/popular' => 'pages#popular'
  get '/home/popular' => 'pages#popular'


  get '/login' => 'session#new'         # login form
  post '/login' => 'session#create'     # performs login, redirect
  delete '/login' => 'session#destroy'  # logout, redirect 

  get '/users/new' => 'users#new'
  post '/users/:id/edit' => 'users#edit' 
  post '/users/:id/likes/:id' => 'likes#show'
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  get '/users/:id/following' => 'following#show'
  get '/users/create'
  get '/users/destroy'

  post '/reviews/:id' => 'reviews#show'

  resources :comments
  resources :lists


  resources :users do
    resources :followers, :following
  end


  resources :reviews do 
    resources :likes, :comments
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :check_if_logged_in, only: [:new, :create]

    def new
        @review = Review.new
    end # new()

    def create
        @review = Review.new review_params 
        @review.user_id = @current_user.id
        
        if params[:review][:image].present?
            response = Cloudinary::Uploader.upload(params[:review][:image])
            @review.image=response['public_id']
        end
        
        if @review.update review_params
            redirect_to home_path
        else 
            p @review.errors 
            redirect_to home_path
        end 

    end # create()

    def show
        @review = Review.find params[:id]
    end # show()

    def destroy
        Review.destroy params[:id]
        redirect_to home_path
    end # destroy()

    def review_params # !!!!!
        params.require(:review).permit(:title,:strength,:weakness,:user_id,:rating)
    end # review_params()

end # ReviewsController

app/views/reviews/new.html.erb
<div class="darkmode"></div>

<% if @current_user.present? %>

    <script>
        const textAreaGrow = function(textArea){
            if (textArea.clientHeight < textArea.scrollHeight){
            textArea.style.height = textArea.scrollHeight + "px";
        }
        }
        // const maxLimit = function(){
        // }

    </script>

    <% if @review.errors.any?  %>
        <strong>ERROR:</strong>
        <% @review.errors.full_messages.each do |e|  %>
            <%= e %>
        <% end %>
    <% end %>

    <%= form_with model: @review, local:true, html:{multipart:true} do |f| %>
        <div class="review-form">
            <div class="article-title">
                <%= f.text_field :title, :maxlength => 35, :minlength => 1, placeholder:'article title', autocomplete:"off" %>
            <%# :onkeyup => "maxLimit(this)" %>
            </div>
            <div class="input">
                <%= f.text_area :rating, rows: 1, :maxlength => 280, placeholder:'type in me', :onkeyup => "textAreaGrow(this)"%>
            </div>
            <div class="review-image"> 
                <%= f.file_field :image %>
            </div>
            <%= f.submit %>
        </div>

    <% end %>
    

<% end %>

app/views/reviews/show.html.erb
<div class="darkmode"></div>

<div class="commentblock">
    <div class="reviewblock comment-show">
        <div class="title">
            <p>
                <%= @review.title%>
            </p>
        </div>
        <div class="userimg">
            <%= cl_image_tag @review.user.image, width:'25'%>
        </div>
        <div class="user">
            <p>
                <%= link_to '@' + @review.user.username.to_s, user_path(@review.user.id) %>
            </p>
        </div>
        <div class="post-image">
            <%= cl_image_tag @review.image %>
        </div>

        <div class="content">
            <p>
                <%=@review.rating%>
            </p>
        </div>

        <div class = "up">
            <% pre_like = @review.likes.find { |like| like.user_id == @current_user.id} %>
            <% if pre_like %>
                <%= button_to '❤️', review_like_path(@review.id, pre_like), method: :delete, class:"likebtn" %>
            <% else %>
                <%= button_to '🤍', review_likes_path(@review.id), method: :post, class:"likebtn"%>
            <% end %>
            <p>
                <%= @review.likes.count %> 
            </p>
        </div>

        <div class="count">
            <p>
                <%= button_to '💬', review_path(@review.id) %>
            </p>

            <p>
                <% unless @review.comments.count == nil %>
                    <%= @review.comments.count %>
                <% end %>
            </p>
        </div>

        <div class="create_time">
            <p>
                <%= @review.created_at.strftime("%H:%M, %Y-%m-%d") %>
            </p>
        </div>
    </div>
</div>

<% unless @review.comments == nil %>
    
    <% @review.comments.each do |e| %>

    <div class="comment">
    <p>
    <% @user = User.find_by! id: e.user_id %>

        <div class="col comment-user align-self-center">
            <%= link_to '@' + @user.username.to_s+':', user_path(@user.id) %>
        </div>

        <div class="col comment-reply align-self-center">
        <p>
            <%= e.reply %>
        </p>
        </div>
    </p>
    </div>
    
    <%# <%= link_to "DELETE", comment_path(e.id), method:'delete' %> 
    <% end %>

<% end %>

<%= form_with model: [@review, @review.comments.build], local:true do |f| %>
    <div class="container"> 
        <div class="row">
            <div class="comment-input">
                <%= f.text_area :reply, :maxlength => 140, placeholder:'write a reply' %>
            </div>
        </div>
        
        <div class="row">
            <%= f.submit 'submit', class:("commentsubmit") %>
        </div>
    </div>

<% end %>

  