config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  post '/' => 'users#search'
  get '/home' => 'pages#home'
  post '/home/all' => 'pages#feed'
  get '/home/all' => 'pages#feed'
  post '/home/popular' => 'pages#popular'
  get '/home/popular' => 'pages#popular'


  get '/login' => 'session#new'         # login form
  post '/login' => 'session#create'     # performs login, redirect
  delete '/login' => 'session#destroy'  # logout, redirect 

  get '/users/new' => 'users#new'
  post '/users/:id/edit' => 'users#edit' 
  post '/users/:id/likes/:id' => 'likes#show'
  post '/users/:id/follow', to: "users#follow", as: "follow_user"
  post '/users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  get '/users/:id/following' => 'following#show'
  get '/users/create'
  get '/users/destroy'

  post '/reviews/:id' => 'reviews#show'

  resources :comments
  resources :lists


  resources :users do
    resources :followers, :following
  end


  resources :reviews do 
    resources :likes, :comments
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>

    <%= yield(:signup) %>
  </head>

  <body>

    <% if @current_user.present? %>
    <div class="navbar">
      <nav class="head">

        <h1 class="blahblah">
          <%= link_to "Re:view-r", home_path %>
        </h1>

        <ul class="searchquery dropdown">
            <button class="search-show">sort feed</button>
              <div class="search-select">
               <li class="dropdown-item">
                <%= link_to "For you", home_path %>
                </li>
               <li class="dropdown-item">
                <%= link_to "All", home_all_path %>
                </li>
                 <li class="dropdown-item">
                <%= link_to "Popular", home_popular_path %>
                </li>
              </div>
        </ul>

        <%= form_with model: @user, local:true do |f| %>
          <div class="search-user">
            <%= f.text_field :search, placeholder:"search for a user"%>
            <%= f.submit '⌕', class:"⌕"%>
          </div>
        <% end %>

        <p class="user-stuff">
          <% if @current_user.image == nil %>
            <% @current_user.update! image: @userimg%>
          <% end %>

          <% if @current_user.setimage %>
            <%= link_to cl_image_tag(@current_user.image, width:"25"), user_path(@current_user.id) %>
          <% else %>
            <%= link_to image_tag(@current_user.image, width:"25"), user_path(@current_user.id) %>
          <% end %>

          <%= link_to '@'+@current_user.username.to_s, user_path(@current_user.id) %>
          <%= link_to ' ♡ ' + @current_user.reviews.select(:like_count).map(&:like_count).sum.to_s, user_path(@current_user.id), class:"like-total"%>
          |
          <%= link_to 'LOGOUT', login_path, method: 'delete' %>
        </p>

          <% else %>
            <%= link_to 'SIGN UP', users_new_path, class:"btn btn-outline-danger" %>
          <% end %>

      </nav>
    </div>
    
    <%= yield %>
  </body>
</html>